name: "Ute2MQTT"
version: "1.1.1"
slug: ute2mqtt
description: >-
  Obtiene datos de consumo eléctrico de UTE (Uruguay) y los publica
  a Home Assistant via MQTT con auto-descubrimiento.
url: "https://github.com/SantiagoSotoC/Ute2MQTT"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
init: false
startup: services
services:
  - mqtt:need
map:
  - type: addon_config
    read_only: false
ports:
  8099/tcp: null
ingress: true
webui: "http://[HOST]:[PORT:8099]"
options:
  mqtt_topic_prefix: "UTE"
  mqtt_discovery_prefix: "homeassistant"
  cron_schedule: "0 8 * * *"
  log_level: "info"
schema:
  mqtt_topic_prefix: str
  mqtt_discovery_prefix: str
  cron_schedule: str
  log_level: list(info|warning|error|debug)
